# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:10
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160820_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
